<?php

/**
 * @file
 * Contains vote_up_down.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vote_up_down_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vote_up_down module.
    case 'help.page.vote_up_down':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a configurable up/down voting widget for other modules to use') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function vote_up_down_theme() {
  return [
    'vote_up_down' => [
      'render element' => 'children',
    ],
  ];
}
