<?php

/**
 * @file
 * Implements the core voting module on top of Voting API.
 */

// Include the theme.inc file.
module_load_include('inc', 'vud', 'vud.theme');

/**
 * @param $account
 *    User Entity Object
 * @param $entity \Drupal\Core\Entity\EntityInterface
 *    Requested Entity Object
 */
function vud_can_vote($account, $entity){
  return $account->hasPermission("add or remove points votes on {$entity->getEntityTypeId()}")
    || $account->hasPermission("add or remove points votes on {$entity->bundle()} of {$entity->getEntityTypeId()}");
}

/**
 * Implements hook_preprocess().
 */
function vud_preprocess(&$variables, $hook) {
  $module_handler = \Drupal::service('module_handler');
  $module_path = $module_handler->getModule('vud')->getPath();
  $variables['#attached']['drupalSettings']['basePath'] = $module_path;
}

/**
 * Implementation of hook_help().
 */
function vud_help($path, $arg) {
  switch ($path) {
    case 'admin.page.vud':
      $output = '<p>'. t('Provides a configurable up/down voting widget for other modules to use.') .'</p>';
      return $output;
    default:
      return FALSE;
      break;
  }
}

